@startuml App

package "Node Js App"{


[User interface vue.js] as ui

node "selenium webDriver" as selenium{

[User interface react.js some] as recorder
[user some] as player
}

}


ui --> recorder
ui --> player

recorder --> recordfile : save file
recordfile --> player : read file




@enduml