export const size = {
    s: {
        size: { title: 'S', value: 'S' },
        breasts: { title: 'Грудь', value: 90 },
        talia: { title: 'Талия', value: 90 },
        hips: { title: 'Бедра', value: 90 },
        lengthskirts: { title: 'Длинаtitle:  юбки', value: 90 },
        lengthpants: { title: 'Длинаtitle:  брюк', value: 90 },
        leanghtBackrest: { title: 'Длинаtitle:  спинки', value: 90 },
        lengthSleeves: { title: 'Длинаtitle:  Рукава', value: 90 },
        hipHeight: { title: 'Высотаtitle:  бедра', value: 90 },
        decolletage: { title: 'Декольте', value: 90 },
        backDepth: { title: 'Глубинаtitle:  спинки', value: 90 },
    },
    m: {
        size: { title: 'M', value: 'M' },
        breasts: { title: 'Грудь', value: 90 },
        talia: { title: 'Талия', value: 90 },
        hips: { title: 'Бедра', value: 90 },
        lengthskirts: { title: 'Длинаtitle:  юбки', value: 90 },
        lengthpants: { title: 'Длинаtitle:  брюк', value: 90 },
        leanghtBackrest: { title: 'Длинаtitle:  спинки', value: 90 },
        lengthSleeves: { title: 'Длинаtitle:  Рукава', value: 90 },
        hipHeight: { title: 'Высотаtitle:  бедра', value: 90 },
        decolletage: { title: 'Декольте', value: 90 },
        backDepth: { title: 'Глубинаtitle:  спинки', value: 90 },
    },
    l: {
        size: { title: 'L', value: 'L' },
        breasts: { title: 'Грудь', value: 90 },
        talia: { title: 'Талия', value: 90 },
        hips: { title: 'Бедра', value: 90 },
        lengthskirts: { title: 'Длинаtitle:  юбки', value: 90 },
        lengthpants: { title: 'Длинаtitle:  брюк', value: 90 },
        leanghtBackrest: { title: 'Длинаtitle:  спинки', value: 90 },
        lengthSleeves: { title: 'Длинаtitle:  Рукава', value: 90 },
        hipHeight: { title: 'Высотаtitle:  бедра', value: 90 },
        decolletage: { title: 'Декольте', value: 90 },
        backDepth: { title: 'Глубинаtitle:  спинки', value: 90 },
    },
    xl: {
        size: { title: 'XL', value: 'XL' },
        breasts: { title: 'Грудь', value: 90 },
        talia: { title: 'Талия', value: 90 },
        hips: { title: 'Бедра', value: 90 },
        lengthskirts: { title: 'Длинаtitle:  юбки', value: 90 },
        lengthpants: { title: 'Длинаtitle:  брюк', value: 90 },
        leanghtBackrest: { title: 'Длинаtitle:  спинки', value: 90 },
        lengthSleeves: { title: 'Длинаtitle:  Рукава', value: 90 },
        hipHeight: { title: 'Высотаtitle:  бедра', value: 90 },
        decolletage: { title: 'Декольте', value: 90 },
        backDepth: { title: 'Глубинаtitle:  спинки', value: 90 },
    },
    xxl: {
        size: { title: 'XXL', value: 'XXL' },
        breasts: { title: 'Грудь', value: 120 },
        talia: { title: 'Талия', value: 120 },
        hips: { title: 'Бедра', value: 120 },
        lengthskirts: { title: 'Длинаtitle:  юбки', value: 120 },
        lengthpants: { title: 'Длинаtitle:  брюк', value: 120 },
        leanghtBackrest: { title: 'Длинаtitle:  спинки', value: 120 },
        lengthSleeves: { title: 'Длинаtitle:  Рукава', value: 120 },
        hipHeight: { title: 'Высотаtitle:  бедра', value: 120 },
        decolletage: { title: 'Декольте', value: 120 },
        backDepth: { title: 'Глубинаtitle:  спинки', value: 120 },
    },
    other: {
        size: { title: 'Свой размер', value: 'Свой размер' },
        breasts: { title: 'Грудь', value: 0 },
        talia: { title: 'Талия', value: 0 },
        hips: { title: 'Бедра', value: 0 },
        lengthskirts: { title: 'Длинаtitle:  юбки', value: 0 },
        lengthpants: { title: 'Длинаtitle:  брюк', value: 0 },
        leanghtBackrest: { title: 'Длинаtitle:  спинки', value: 0 },
        lengthSleeves: { title: 'Длинаtitle:  Рукава', value: 0 },
        hipHeight: { title: 'Высотаtitle:  бедра', value: 0 },
        decolletage: { title: 'Декольте', value: 0 },
        backDepth: { title: 'Глубинаtitle:  спинки', value: 0 },
    },
}
